export const classData = [
  {
    code: "HCM22_FR.BA_02",
    name: "Business Foundation",
    studyForm: 'intern',
    rank: 'monday',
    session: "morning",
    time: "9:00",
  },
  {
    code: "HN22_FR_DevOps_01",
    name: "DevOps Foundation",
    studyForm: 'fresher',
    rank: 'wednesday',
    session: "morning",
    time: "9:00",
  },
  {
    code: "HN22_FR_DevOps_02",
    name: "DevOps",
    studyForm: 'fresher',
    rank: "thursday",
    session: "morning",
    time: "10:00",
  },
  {
    code: "DN22_FR_DevOps_05",
    name: "Develop Operation Foundation",
    studyForm: 'fresher',
    rank: "friday",
    session: "morning",
    time: "9:00",
  },
  {
    code: "DN22_FR.NET_02",
    name: ".NET Foundation",
    studyForm: 'intern',
    rank: "friday",
    session: "noon",
    time: "14:00",
  },
  {
    code: "QN22_FR_DevOps_01",
    name: "DevOps Foundation",
    studyForm: 'fresher',
    rank: "tuesday",
    session: "noon",
    time: "14:00",
  },
  {
    code: "HCM22_FR.O DevOps_02",
    name: "DevOps",
    studyForm: 'intern',
    rank: "tuesday",
    session: "noon",
    time: "15:00",
  },
  {
    code: "HCM22_FR.BA_02",
    name: "Business Foundation",
    studyForm: 'offline',
    rank: "thursday",
    session: "night",
    time: "18:00",
  },
  {
    code: "HN22_FR.BA_02",
    name: "Business Foundation",
    studyForm: 'offline',
    rank: "thursday",
    session: "night",
    time: "18:00",
  },
  {
    code: "DN22_FR.NET_02",
    name: ".NET Foundation",
    studyForm: 'online',
    rank: "thursday",
    session: "night",
    time: "19:00",
  },
  {
    code: "QN22_FR_DevOps_01",
    name: "DevOps Foundation",
    studyForm: 'offline',
    rank: "friday",
    session: "night",
    time: "19:00",
  },
];
